### ISSUE TITLE
NavScreen: Docks and Docking Labels only drawn when zoomed out.

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [new-frontiers-14/frontier-station-14#2775]
## Description
~~After the update that added Gasbenders and atmospheric mining, the indicator arrows on the NAV screen have been offset, making it difficult to identify ships. The distance appears to be accurate.~~ (Fixed by https://github.com/new-frontiers-14/frontier-station-14/pull/2726)

Additionally, the square docking indicators and the labels are occasionally clipped and hidden.

**Reproduction**
Use the nav console.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b05e382c-36bb-46d5-bd6a-76ac2775ce50)

Bahama Mama's indicator is shown towards the bottom of the screen rather than to the left, where the station actually is. Additionally the lower two docking ports are not visible.

**Additional context**

Running on Arch Linux via the Flatpak distribution of SS14. Haven't tested in other environments.

**Comment by dvir001** [comment]
Can you confirm this is active now since we already fixed it.

**Comment by ColonelThirtyTwo** [comment]
It's still happening on Maunder as I write. Mass scanner is also affected. At 175% UI scale.

![Image](https://github.com/user-attachments/assets/2c98284d-d0ee-4556-bfd5-a1a45da31026)

100% scale fixes it, but is tiny on a 4K monitor:

![Image](https://github.com/user-attachments/assets/e0f3a361-2bd2-43d9-bdc6-334c1ec8ea0e)

**Comment by ColonelThirtyTwo** [comment]
Nevermind, the update that just went out seems to have fixed it.

**Comment by ColonelThirtyTwo** [comment]
The IFF arrows are rendering correctly but the docking indicators and labels are still being clipped off at certain positions, so I'm going to reopen this.

**Comment by whatston3** [comment]
> The IFF arrows are rendering correctly but the docking indicators and labels are still being clipped off at certain positions, so I'm going to reopen this.

Seems fine on my end even after changing the UI scale.  Got a screenshot?

Your original images don't seem "clipped off".

**Comment by ColonelThirtyTwo** [comment]
I'll try to get a better screenshot this evening, but even when zoomed out, docks will be hidden in certain areas of the viewport at 175% UI scale.

**Comment by ColonelThirtyTwo** [comment]
https://github.com/whatston3/frontier-station-14/blob/a5190582f25bdcb7e4d072d62298d99b3ff125e2/Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs#L377C14-L377C24

I suspect the culling code around here also needs to be adjusted to take the UI scale into account.

**Comment by ColonelThirtyTwo** [comment]
![Image](https://github.com/user-attachments/assets/05f6fa5b-9f81-40ed-bd55-36cf72c4da49)

Image of FO zoomed out. Only three docks are labeled.
